/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:78eafbba-d179-459d-aaea-ddb221c4fea9",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_GCdRmEmer",
    "aws_user_pools_web_client_id": "1cf70c3og6gthoj6viukjhs114",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "backend",
            "endpoint": "https://vaets7agul.execute-api.ap-southeast-2.amazonaws.com/dev",
            "region": "ap-southeast-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://pb7awya2e5fwhednzwxo2oqhje.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
