export default {
  ENV: process.env.ENV,
  TABLE_REGION: process.env.TABLE_REGION,
  STRIPE_KEY: process.env.STRIPE_KEY,
  CLIENT_TABLE_NAME: process.env.CLIENT_TABLE_NAME,
  THERAPIST_TABLE_NAME: process.env.THERAPIST_TABLE_NAME,
  THERAPIST_CLIENT_TABLE_NAME: process.env.THERAPIST_CLIENT_TABLE_NAME,
  API_API_GRAPHQLAPIENDPOINTOUTPUT: process.env.API_API_GRAPHQLAPIENDPOINTOUTPUT,
};
